name: "Create/Update tag"
description: "Creates or updates a tag for a given commit."
author: "Rick Staa"
inputs:
  github_token:
    description: "GITHUB_TOKEN. Optional if you use checkout@v2 action."
    default: "${{ github.token }}"
  tag:
    description: "Tag you want to create or update."
    required: true
  message:
    description: "Tag message."
    required: false
  commit_sha:
    description: The commit SHA hash on which you want to push the tag. Uses latest commit by default.
    required: false
  force_push_tag:
    description: "Optional. Force push the tag. Defaults to 'false'."
    required: false
    default: "false"
  tag_exists_error:
    description: "Optional. Whether to throw an error when the tag already exists. Defaults to 'true'."
    required: false
    default: "true"
  no_verify_tag:
    description: "Optional. Skips verifying when pushing the tag. Defaults to 'false'."
    required: false
    default: "false"
  gpg_private_key:
    description: "Optional. GPG key to sign the tag with."
    required: false
  gpg_passphrase:
    description: "Optional. GPG key passphrase."
    required: false
outputs:
  tag_exists:
    description: "Whether the tag already existed."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "tag"
  color: "blue"
